version: '3'

services:
  db:
    image: "postgres"
    container_name: "db"
    volumes:
      - ./db:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9V%=JftDf<
  app:
    build: .
    container_name: "app"
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
