version: '3'

services:
#  db:
#    image: "postgres"
#    container_name: "db"
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 9V%=JftDf<
#  app:
#    build: .
#    container_name: "app"
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#    depends_on:
#      - db

  db:
    image: mysql:latest
    container_name: "db-mysql"
    hostname: db-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: DB
      MYSQL_USER: root
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_PASSWORD: teste
#    networks:
#      - external-api
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8080:8080"
    restart: always
    environment:
      WAIT_HOSTS: db:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql
        :3306/DB=true&failOverReadOnly=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: teste
#    depends_on:
#      - db
#    networks:
#      - external-api
#networks:
#  external-api:
#    driver: bridge